### PR TITLE
refactor topic_checking to simplify booleans

### PR DESCRIPTION
**Pull request by HerrMuellerluedenscheid**
@FlorianLudwig please have a look. I find this much easier to understand than the other way around.

### CODE REVIEW

**Comment by HerrMuellerluedenscheid** [comment]
@FlorianLudwig converting to draft. I want to make sure that this function gets properly tested beforehand.

**Comment by FlorianLudwig** [comment]
@HerrMuellerluedenscheid the code changes semantics:

From `broker.topic_filtering`:
```
         - True if MQTT client can be subscribed to the topic
         - False if MQTT client is not allowed to subscribe to the topic
         - None if topic filtering can't be achieved (then plugin result is then ignored)
```

You removed the `None` case. Basically merging it into he `True` case. A change I agree with :) But please update the comment in `broker.py` accordingly.

**Comment by FlorianLudwig** [comment]
@HerrMuellerluedenscheid I still think this is a good change! Especially now with 0.10 out the door it is a good time to do some more refactoring!

Do you intend to carry this one forward?

**Comment by plbertrand** [comment]
I've create #103 but I'm happy to push the merge commit here if you want to give me write access to this branch.

**Comment by HerrMuellerluedenscheid** [comment]
Superseded by #103

**Pull request closed without merging**
