### PR TITLE
move to poetry

### LINKED ISSUE #6: provide list of pinned dependencies for development
During development we should have a set of pinned dependencies for a reproducible development and CI setup.

Options:

- `requirements.txt`
- `pipenv`
- `poetry`

I am in a love/hate relationship with poetry and would go with that :)

### PR DESCRIPTION
**Pull request by FlorianLudwig**
closes #6 

Draft for docs:
---
# Requirements

1. python installed
2. [poetry](https://python-poetry.org/docs/#installation) installed

# Usage

Poetry will create a virtual environment for you

Install:
```
poetry install --no-dev
```

Usage:
```
poetry run hbmqtt
poetry run hbmqtt_pub
poetry run hbmqtt_sub
```

Or you can enter the virtual enviroment via:
```
poetry shell
```

And then run the commands without prefixing them with `poetry run`

# Development setup

Install with:
```
poetry install
```
This will install all dependencies needed for development.
A virtual environment will be created and can be entered with `poetry shell`.

Afterwards you can use `pytest` etc.

If you have multiple python installations you can choose which one to use with poetry with `poetry env`, this is helpful for switching between python versions for testing.

### CODE REVIEW

**Review by HerrMuellerluedenscheid — COMMENTED** [review]
Nice. Works like charm. Only thought I have is: isn't package installing using pip more popular than poetry (which I think uses pip under the hood, right)? Thus, wouldn't it be reasonable to run the test based on the pip installed dependencies as well as against the ones locked by poetry?

**Comment by FlorianLudwig** [comment]
I like the idea of testing different versions of our dependencies, but we have to be careful to not have our testing matrix explode.

Always running against "latest version" is something I do not like, as it makes ci pipelines non reproducible. 

We might want to setup something like `renovate`

**Comment by HerrMuellerluedenscheid** [comment]
> I like the idea of testing different versions of our dependencies, but we have to be careful to not have our testing matrix explode.
> 
> Always running against "latest version" is something I do not like, as it makes ci pipelines non reproducible.
> 
> We might want to setup something like `renovate`

`renovate` sounds like the way to go here. :+1:

**Review by HerrMuellerluedenscheid — APPROVED** [review]

**Comment by HerrMuellerluedenscheid** [comment]
nice!

**Comment by FlorianLudwig** [comment]
@HerrMuellerluedenscheid I created https://github.com/Yakifo/amqtt/issues/48 about the CI setup and dependency versions.

**Comment by shipmints** [comment]
For what it's worth, we use hbmqtt as an embedded library and where the project's overall dependencies are managed using https://github.com/jazzband/pip-tools specifying only explicit dependencies and letting the pip-tools manage transitive dependencies. We freeze the resulting generated pip package list including with hash signatures and only update dependencies when absolutely needed.

Moving to poetry is fine with us as long as our ability to continue to use aiomqtt (or whatever name ultimately gets chosen) on an embedded basis and with potentially shared dependencies among all the other modules we use remains possible and doesn't force a wholesale move to poetry for our own project.

**Comment by FlorianLudwig** [comment]
@shipmints poetry is not needed for using aMQTT.

Poetry is needed when developing on it.

For projects depending on it:
 * The wheels can be installed with any pip-conformant tool
 * Source installations are possible with any somewhat new pip version too - it should be PEP517 and PEP518 that the tooling must support.

**Comment by shipmints** [comment]
Sounds workable. Thank you.

**Pull request merged**
