### PR TITLE
black samples and setup

### PR DESCRIPTION
**Pull request by HerrMuellerluedenscheid**

### CODE REVIEW

**Comment by HerrMuellerluedenscheid** [comment]
@FlorianLudwig after I screwed up the first `black`ening I realized that the line length set in `flake8` and `black` were inconsistent. Now is a good point in time to discuss this: line-length. 96, 127, 80, 79, something else? These days I'm up for long lines.

**Comment by FlorianLudwig** [comment]
In most projects I use the [default of black](https://black.readthedocs.io/en/stable/the_black_code_style.html#line-length) - 88. 

The reasoning for "not going with long lines" is that 

a) reminds people that long lines are hard to read and splitting up code into multiple steps with temp variables makes them more readable in like 99% of cases.

b) if the length is needed because of indentation I would go with the same argument - that is too much nesting, clean up the code instead. As the linux developer puts it:

> Now, some people will claim that having 8-character indentations makes the code move too far to the right, and makes it hard to read on a 80-character terminal screen. The answer to that is that if you need more than 3 levels of indentation, you’re screwed anyway, and should fix your program.

c) I like to be able to code on my laptop with two files open next to each other and having all the UI overhead of $ide.

**Comment by HerrMuellerluedenscheid** [comment]
> In most projects I use the [default of black](https://black.readthedocs.io/en/stable/the_black_code_style.html#line-length) - 88.
> 
> The reasoning for "not going with long lines" is that
> 
> a) reminds people that long lines are hard to read and splitting up code into multiple steps with temp variables makes them more readable in like 99% of cases.
> 
> b) if the length is needed because of indentation I would go with the same argument - that is too much nesting, clean up the code instead. As the linux developer puts it:
> 
> > Now, some people will claim that having 8-character indentations makes the code move too far to the right, and makes it hard to read on a 80-character terminal screen. The answer to that is that if you need more than 3 levels of indentation, you’re screwed anyway, and should fix your program.
> 
> c) I like to be able to code on my laptop with two files open next to each other and having all the UI overhead of $ide.

Ok. Sounds fair. I'll switch to blacks default

**Comment by HerrMuellerluedenscheid** [comment]
@FlorianLudwig I updated CI and code at line length 88. please re-review.

**Review by FlorianLudwig — APPROVED** [review]

**Pull request merged**
